# Generated by Django 2.0.7 on 2018-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
