# Generated by Django 2.0.7 on 2018-11-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20181119_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
